'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),json=p=>JSON.parse(read(p));
const tech=/(source coordinate|street address not asserted|exact coordinates retained|\bPF\d+\b|current named member\/resource|public irs filing address geocoded|assigned community)/i;
test('R1360 Factory duplicate resolves canonically',()=>{const s=json('dist/data/profile-identity-safety.json');assert.equal(s.schemaVersion,'franklin.profile-identity-safety.v1');assert.equal(s.aliases['FR-ORG-adba2e46b06e6112'],'FR-ORG-0086-the-factory-at-franklin');assert.ok(s.counts.aliases>=1);assert.ok(s.counts.holds>=1)});
test('R1360 discovery has no technical location prose',()=>{for(const name of fs.readdirSync(path.join(root,'dist/data/discovery')).filter(x=>/^profiles-\d+\.json$/.test(x))){const d=json('dist/data/discovery/'+name);for(const r of d.records){assert.doesNotMatch(String(r[2]||''),tech,name+' '+r[0]);assert.notEqual(r[0],'FR-ORG-adba2e46b06e6112')}}});
test('R1360 claim shards exclude aliases and identity-review holds',()=>{const s=json('dist/data/profile-identity-safety.json'),blocked=new Set([...Object.keys(s.aliases),...Object.keys(s.holds)]);for(const name of fs.readdirSync(path.join(root,'dist/data')).filter(x=>/^franklin-profiles-\d+\.json$/.test(x))){const d=json('dist/data/'+name);for(const r of d.records){assert.equal(blocked.has(r.i),false,name+' '+r.i);assert.doesNotMatch(String(r.l||''),tech)}}});
test('R1360 alias page resolves and cannot be claimed',()=>{const h=read('dist/profiles/FR-ORG-adba2e46b06e6112/index.html');assert.match(h,/FR-ORG-0086-the-factory-at-franklin/);assert.match(h,/Profile identity updated/);assert.doesNotMatch(h,/Claim or manage this profile/);assert.doesNotMatch(h,/Source coordinate/)});
test('R1360 claim UX explains verification and separates reviewer tools',()=>{const s=read('dist/assets/membership-live.js');assert.match(s,/What happens next/);assert.match(s,/Continue only if you are authorized to manage/);assert.match(s,/does not give you control of the profile/);assert.match(s,/We found an existing Franklin account for this email\. We switched you to Sign in\./);assert.match(s,/reviewerAccessAvailable===true&&!state\.profileMode/);assert.match(s,/Start management verification/);assert.doesNotMatch(s,/const connect=button\('Continue with this profile'/)});
