'use strict';
const http = require('node:http');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const {Pool} = require('pg');
const {URL} = require('node:url');
const {COMMUNITY, PRICE_AUTHORITY, FOUNDING, getPlan, publicCatalog} = require('./lib/catalog');
const {sha256, randomToken, hashPassword, verifyPassword, verifySignedRequest, verifyStripeSignature, signAssertion, safeEqual} = require('./lib/security');
const {initialState, applyEvent, accessAllowed, mapStripeEvent} = require('./lib/lifecycle');

const RELEASE = process.env.LOCAL_RELEASE || 'FR-NAV1.3.0-CANDIDATE-R28';
const SCHEMA_VERSION = 'FRANKLIN_COMMERCE_SCHEMA_2';
const PORT = Number(process.env.PORT || 10000);
const PUBLIC_ORIGIN = String(process.env.PUBLIC_ORIGIN || 'https://franklinnavigator.com').replace(/\/$/, '');
const ALLOWED_ORIGINS = new Set([PUBLIC_ORIGIN, 'https://www.franklinnavigator.com', ...(process.env.ADDITIONAL_ALLOWED_ORIGINS || '').split(',').map(x=>x.trim()).filter(Boolean)]);
const DATABASE_URL = String(process.env.DATABASE_URL || '').trim();
const SESSION_SECRET = String(process.env.SESSION_SECRET || '').trim();
const LOCAL_ASSERTION_SECRET = String(process.env.LOCAL_ASSERTION_SECRET || '').trim();
const SRE_SHARED_SECRET = String(process.env.SRE_SHARED_SECRET || '').trim();
const STRIPE_WEBHOOK_SECRET = String(process.env.STRIPE_WEBHOOK_SECRET || '').trim();
const STRIPE_ACCOUNT_ID = String(process.env.STRIPE_ACCOUNT_ID || 'acct_1TZU2TRxNra9nizo').trim();
const STRIPE_PORTAL_LOGIN_URL = String(process.env.STRIPE_PORTAL_LOGIN_URL || '').trim();
const ADMIN_TOKEN = String(process.env.ADMIN_TOKEN || '').trim();
const COMMERCE_ENABLED = /^(1|true|yes|on)$/i.test(String(process.env.COMMERCE_ENABLED || 'false'));
const COOKIE_NAME = '__Host-franklin_session';
const SESSION_DAYS = Math.max(1, Math.min(30, Number(process.env.SESSION_DAYS || 14)));
const BODY_LIMIT = 256 * 1024;
const PROFILE_RE = /^FR-[A-Z0-9]+-[A-Za-z0-9][A-Za-z0-9._-]{2,100}$/;
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const pool = DATABASE_URL ? new Pool({connectionString:DATABASE_URL,max:10,idleTimeoutMillis:30000,connectionTimeoutMillis:8000,ssl:process.env.PGSSL_DISABLE==='true'?false:{rejectUnauthorized:false}}) : null;
const rateWindows = new Map();
let schemaDigest = null;
let readyError = null;

const nowIso = () => new Date().toISOString();
const newId = prefix => `${prefix}_${crypto.randomUUID().replaceAll('-', '')}`;
const normalizeEmail = value => String(value || '').trim().toLowerCase();
const safeText = (value, max=1000) => String(value || '').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);
const publicError = (code,message,status=400) => Object.assign(new Error(message),{code,status});
const requestId = () => newId('req');
const clientKey = req => sha256(String(req.headers['x-forwarded-for'] || req.socket.remoteAddress || 'unknown').split(',')[0].trim()).slice(0,24);
const configStatus = () => {
  const required = {DATABASE_URL,SESSION_SECRET,LOCAL_ASSERTION_SECRET,SRE_SHARED_SECRET,ADMIN_TOKEN};
  const missing = Object.entries(required).filter(([key,value]) => !value || (key !== 'DATABASE_URL' && value.length < 32)).map(([key])=>key);
  return {ok:missing.length===0,missing};
};
function setCors(req,res) {
  const origin=String(req.headers.origin || '');
  if (origin && ALLOWED_ORIGINS.has(origin)) {
    res.setHeader('Access-Control-Allow-Origin',origin);
    res.setHeader('Access-Control-Allow-Credentials','true');
    res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization, X-Franklin-Timestamp, X-Franklin-Signature, Stripe-Signature');
    res.setHeader('Access-Control-Expose-Headers','X-Request-Id');
    res.setHeader('Vary','Origin');
  }
}
function securityHeaders(req,res) {
  setCors(req,res);
  res.setHeader('X-Content-Type-Options','nosniff');
  res.setHeader('X-Frame-Options','DENY');
  res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');
  res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=(), payment=(self)');
  res.setHeader('Content-Security-Policy',"default-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'self' https://checkout.stripe.com https://billing.stripe.com");
  res.setHeader('Cache-Control','no-store');
  res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');
}
function sendJson(req,res,status,payload,reqId) {
  const body=JSON.stringify(payload); securityHeaders(req,res); res.statusCode=status;
  res.setHeader('Content-Type','application/json; charset=utf-8'); res.setHeader('Content-Length',Buffer.byteLength(body));
  if(reqId)res.setHeader('X-Request-Id',reqId); res.end(body);
}
function sendEmpty(req,res,status=204){securityHeaders(req,res);res.statusCode=status;res.end();}
function enforceOrigin(req){if(!['POST','PUT','PATCH','DELETE'].includes(req.method))return;const origin=req.headers.origin;if(origin&&!ALLOWED_ORIGINS.has(origin))throw publicError('ORIGIN_NOT_ALLOWED','This request origin is not allowed.',403);}
function rateLimit(key,limit,windowMs){const now=Date.now();let row=rateWindows.get(key);if(!row||row.resetAt<=now){row={count:0,resetAt:now+windowMs};rateWindows.set(key,row);}row.count++;return row.count<=limit;}
setInterval(()=>{const now=Date.now();for(const [key,row] of rateWindows)if(row.resetAt<=now)rateWindows.delete(key);},60000).unref();
async function readBody(req,raw=false){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>BODY_LIMIT)throw publicError('REQUEST_TOO_LARGE','Request is too large.',413);chunks.push(chunk);}const buffer=Buffer.concat(chunks);if(raw)return buffer;if(!buffer.length)return{};if(!String(req.headers['content-type']||'').toLowerCase().includes('application/json'))throw publicError('JSON_REQUIRED','Use a JSON request body.',415);try{return JSON.parse(buffer.toString('utf8'));}catch{throw publicError('JSON_INVALID','The JSON request body is invalid.');}}
async function query(text,values=[]){if(!pool)throw publicError('DATABASE_NOT_CONFIGURED','Membership service is not ready.',503);return pool.query(text,values);}
async function tx(fn){if(!pool)throw publicError('DATABASE_NOT_CONFIGURED','Membership service is not ready.',503);const client=await pool.connect();try{await client.query('begin');const out=await fn(client);await client.query('commit');return out;}catch(error){await client.query('rollback').catch(()=>{});throw error;}finally{client.release();}}
function parseCookies(header){const out={};for(const part of String(header||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim());}return out;}
function setSessionCookie(res,token,expiresAt){const maxAge=Math.max(0,Math.floor((new Date(expiresAt).getTime()-Date.now())/1000));res.setHeader('Set-Cookie',`${COOKIE_NAME}=${token}; Path=/; Max-Age=${maxAge}; Expires=${new Date(expiresAt).toUTCString()}; HttpOnly; Secure; SameSite=None; Partitioned`);}
function clearSessionCookie(res){res.setHeader('Set-Cookie',`${COOKIE_NAME}=; Path=/; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT; HttpOnly; Secure; SameSite=None; Partitioned`);}
async function createSession(req,res,accountId){const token=randomToken();const expiresAt=new Date(Date.now()+SESSION_DAYS*86400000).toISOString();await query(`insert into franklin_sessions(session_hash,account_id,expires_at,ip_prefix_hash,user_agent_hash) values($1,$2,$3,$4,$5)`,[sha256(`${SESSION_SECRET}:${token}`),accountId,expiresAt,clientKey(req),sha256(req.headers['user-agent']||'').slice(0,32)]);setSessionCookie(res,token,expiresAt);}
async function sessionFor(req){const token=parseCookies(req.headers.cookie)[COOKIE_NAME];if(!token)return null;const result=await query(`select s.account_id,a.email,a.display_name,a.preferred_language,a.email_verified_at from franklin_sessions s join franklin_accounts a using(account_id) where s.session_hash=$1 and s.expires_at>now() and a.state='ACTIVE'`,[sha256(`${SESSION_SECRET}:${token}`)]);return result.rows[0]||null;}
async function requireSession(req){const session=await sessionFor(req);if(!session)throw publicError('AUTH_REQUIRED','Sign in to continue.',401);return session;}
function normalizeProfile(value){const id=String(value||'').trim();if(!PROFILE_RE.test(id))throw publicError('PROFILE_ID_INVALID','Choose a valid Franklin Navigator profile.');return id;}
async function audit(client,actorType,actorRef,actionType,targetType,targetRef,reqId,context={}){await client.query(`insert into franklin_audit_log(audit_id,actor_type,actor_ref_hash,action_type,target_type,target_ref_hash,request_id,safe_context) values($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,[newId('audit'),actorType,actorRef?sha256(actorRef):null,actionType,targetType||null,targetRef?sha256(targetRef):null,reqId||null,JSON.stringify(context)]);}
async function initializeDatabase(){const cfg=configStatus();if(!cfg.ok)throw new Error(`missing_required_environment:${cfg.missing.join(',')}`);const schema=fs.readFileSync(path.join(__dirname,'schema','001_init.sql'),'utf8');schemaDigest=sha256(schema);await pool.query(schema);await pool.query(`insert into franklin_schema_migrations(version,digest_sha256) values($1,$2) on conflict(version) do update set digest_sha256=excluded.digest_sha256`,[SCHEMA_VERSION,schemaDigest]);}
function addLinkParams(url,params){const target=new URL(url);for(const [key,value]of Object.entries(params))if(value)target.searchParams.set(key,value);return target.toString();}
async function membershipForAccount(accountId){const result=await query(`select m.*,e.access_state,e.growth_desk,e.rich_profile,e.local_visibility_tools from franklin_memberships m left join franklin_entitlements e using(membership_id) where m.account_id=$1 order by m.updated_at desc limit 1`,[accountId]);return result.rows[0]||null;}
async function resolveEventContext(client,event){const object=event.data?.object||{};const intentId=String(object.client_reference_id||'').trim();if(intentId){const found=await client.query(`select * from franklin_checkout_intents where intent_id=$1`,[intentId]);if(found.rowCount)return {intent:found.rows[0],membership:null};}
  const subscriptionId=String(object.subscription||(object.object==='subscription'?object.id:object.parent?.subscription_details?.subscription)||'').trim();const customerId=String(object.customer||'').trim();
  const found=await client.query(`select * from franklin_memberships where ($1<>'' and stripe_subscription_id=$1) or ($2<>'' and stripe_customer_id=$2) order by updated_at desc limit 1`,[subscriptionId,customerId]);return {intent:null,membership:found.rows[0]||null};}
async function processCanonicalEvent(client,eventKey,source,event,payloadHash,reqId){const mapped=mapStripeEvent(event);if(!mapped)return {state:'IGNORED'};const context=await resolveEventContext(client,event);let membership=context.membership;let accountId=membership?.account_id||context.intent?.account_id;let profileId=membership?.profile_id||context.intent?.profile_id;let lookupKey=membership?.lookup_key||context.intent?.lookup_key;if(!accountId||!profileId||!getPlan(lookupKey)){await client.query(`insert into franklin_dead_letters(dead_letter_id,source_event_key,reason_code,safe_context) values($1,$2,'MEMBERSHIP_CONTEXT_NOT_FOUND',$3::jsonb)`,[newId('dead'),eventKey,JSON.stringify({eventType:event.type})]);return{state:'DEAD_LETTER'};}
  const object=event.data?.object||{};const subscriptionId=String(object.subscription||(object.object==='subscription'?object.id:object.parent?.subscription_details?.subscription)||mapped.subscriptionId||'').trim()||null;const customerId=String(object.customer||membership?.stripe_customer_id||'').trim()||null;
  if(!membership){const id=newId('member');const start=applyEvent(initialState(),{...mapped,subscriptionId});await client.query(`insert into franklin_memberships(membership_id,account_id,profile_id,lookup_key,stripe_customer_id,stripe_subscription_id,status,failure_count,cancel_at_period_end,current_period_end,last_event_created) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,accountId,profileId,lookupKey,customerId,subscriptionId,start.status,start.failureCount,start.cancelAtPeriodEnd,start.currentPeriodEnd,start.lastEventCreated]);membership={membership_id:id,account_id:accountId,profile_id:profileId,lookup_key:lookupKey,...start,stripe_customer_id:customerId,stripe_subscription_id:subscriptionId};}
  else {const next=applyEvent({status:membership.status,failureCount:membership.failure_count,cancelAtPeriodEnd:membership.cancel_at_period_end,currentPeriodEnd:membership.current_period_end,lastEventCreated:Number(membership.last_event_created||0),subscriptionId:membership.stripe_subscription_id},{...mapped,subscriptionId});await client.query(`update franklin_memberships set stripe_customer_id=coalesce($2,stripe_customer_id),stripe_subscription_id=coalesce($3,stripe_subscription_id),status=$4,failure_count=$5,cancel_at_period_end=$6,current_period_end=coalesce($7,current_period_end),last_event_created=$8,updated_at=now() where membership_id=$1`,[membership.membership_id,customerId,subscriptionId,next.status,next.failureCount,next.cancelAtPeriodEnd,next.currentPeriodEnd,next.lastEventCreated]);membership={...membership,status:next.status,failure_count:next.failureCount,cancel_at_period_end:next.cancelAtPeriodEnd,current_period_end:next.currentPeriodEnd,last_event_created:next.lastEventCreated};}
  const allowed=accessAllowed(membership.status,membership.current_period_end);await client.query(`insert into franklin_entitlements(membership_id,access_state,growth_desk,rich_profile,local_visibility_tools,expires_at) values($1,$2,$3,$3,$3,$4) on conflict(membership_id) do update set access_state=excluded.access_state,growth_desk=excluded.growth_desk,rich_profile=excluded.rich_profile,local_visibility_tools=excluded.local_visibility_tools,expires_at=excluded.expires_at,updated_at=now()`,[membership.membership_id,allowed?'ACTIVE':'INACTIVE',allowed,membership.current_period_end||null]);
  if(context.intent)await client.query(`update franklin_checkout_intents set state=$2,stripe_checkout_session_id=coalesce($3,stripe_checkout_session_id),stripe_customer_id=coalesce($4,stripe_customer_id),stripe_subscription_id=coalesce($5,stripe_subscription_id),updated_at=now() where intent_id=$1`,[context.intent.intent_id,allowed?'FULFILLED':'RECEIVED',object.object==='checkout.session'?object.id:null,customerId,subscriptionId]);
  await audit(client,'SYSTEM',source,'MEMBERSHIP_EVENT_APPLIED','MEMBERSHIP',membership.membership_id,reqId,{eventType:event.type,status:membership.status});return{state:'PROCESSED',membershipId:membership.membership_id,status:membership.status};}
async function handleEvent({eventKey,source,event,payloadHash,reqId}){return tx(async client=>{const inserted=await client.query(`insert into franklin_event_ledger(event_key,source,event_type,payload_sha256,event_created,processing_state) values($1,$2,$3,$4,$5,'RECEIVED') on conflict(event_key) do nothing returning event_key`,[eventKey,source,event.type,payloadHash,Number(event.created||0)]);if(!inserted.rowCount)return{duplicate:true};try{const result=await processCanonicalEvent(client,eventKey,source,event,payloadHash,reqId);await client.query(`update franklin_event_ledger set processing_state=$2,processed_at=now(),membership_id=$3 where event_key=$1`,[eventKey,result.state,result.membershipId||null]);return result;}catch(error){await client.query(`update franklin_event_ledger set processing_state='FAILED',processed_at=now(),safe_context=$2::jsonb where event_key=$1`,[eventKey,JSON.stringify({errorCode:error.code||error.constructor?.name})]);throw error;}});}
async function route(req,res){const reqId=requestId();try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='OPTIONS'){const origin=String(req.headers.origin||'');if(origin&&!ALLOWED_ORIGINS.has(origin))throw publicError('ORIGIN_NOT_ALLOWED','This request origin is not allowed.',403);return sendEmpty(req,res,204);}enforceOrigin(req);
  if(req.method==='GET'&&url.pathname==='/health'){let database=false;try{database=Boolean((await query('select 1 ok')).rowCount);}catch{}const cfg=configStatus();const healthy=cfg.ok&&database&&!readyError;return sendJson(req,res,healthy?200:503,{ok:healthy,release:RELEASE,community:COMMUNITY,commerceEnabled:COMMERCE_ENABLED,databaseConfigured:Boolean(DATABASE_URL),database,startupReady:!readyError,missing:cfg.missing,uptimeSeconds:Math.floor(process.uptime())},reqId);}
  if(req.method==='GET'&&url.pathname==='/ready'){let database=false,links=0,migration=null;try{database=Boolean((await query('select 1 ok')).rowCount);links=Number((await query(`select count(*)::int n from franklin_payment_links where active=true`)).rows[0]?.n||0);migration=(await query(`select version,digest_sha256,applied_at from franklin_schema_migrations where version=$1`,[SCHEMA_VERSION])).rows[0]||null;}catch{}const cfg=configStatus();const infrastructureReady=cfg.ok&&database&&links===4&&Boolean(STRIPE_WEBHOOK_SECRET)&&Boolean(STRIPE_PORTAL_LOGIN_URL)&&Boolean(migration);return sendJson(req,res,infrastructureReady?200:503,{ok:infrastructureReady,release:RELEASE,community:COMMUNITY,schemaVersion:SCHEMA_VERSION,schemaDigest,migration,database,paymentLinkCount:links,stripeWebhookConfigured:Boolean(STRIPE_WEBHOOK_SECRET),portalLoginConfigured:Boolean(STRIPE_PORTAL_LOGIN_URL),commerceEnabled:COMMERCE_ENABLED,liveCheckoutEnabled:infrastructureReady&&COMMERCE_ENABLED,missing:cfg.missing,startupError:readyError?String(readyError.message||readyError):null},reqId);}
  if(req.method==='GET'&&url.pathname==='/api/catalog')return sendJson(req,res,200,publicCatalog(),reqId);
  if(req.method==='POST'&&url.pathname==='/api/accounts/register'){if(!rateLimit(`register:${clientKey(req)}`,5,3600000))throw publicError('RATE_LIMITED','Too many attempts. Try again later.',429);const body=await readBody(req);const email=normalizeEmail(body.email);if(!EMAIL_RE.test(email))throw publicError('EMAIL_INVALID','Enter a valid email.');const passwordHash=await hashPassword(body.password);const accountId=newId('acct');await tx(async client=>{await client.query(`insert into franklin_accounts(account_id,community,email,email_normalized,password_hash,display_name,preferred_language) values($1,$2,$3,$3,$4,$5,$6)`,[accountId,COMMUNITY,email,passwordHash,safeText(body.displayName,120)||null,['ENGLISH','SPANISH','BILINGUAL'].includes(String(body.preferredLanguage||'').toUpperCase())?String(body.preferredLanguage).toUpperCase():'ENGLISH']);await audit(client,'ACCOUNT',accountId,'ACCOUNT_CREATED','ACCOUNT',accountId,reqId);});await createSession(req,res,accountId);return sendJson(req,res,201,{ok:true,accountId},reqId);}
  if(req.method==='POST'&&url.pathname==='/api/accounts/login'){if(!rateLimit(`login:${clientKey(req)}`,10,900000))throw publicError('RATE_LIMITED','Too many attempts. Try again later.',429);const body=await readBody(req);const result=await query(`select account_id,password_hash from franklin_accounts where email_normalized=$1 and state='ACTIVE'`,[normalizeEmail(body.email)]);const account=result.rows[0];if(!account||!await verifyPassword(body.password,account.password_hash))throw publicError('LOGIN_INVALID','Email or password is incorrect.',401);await createSession(req,res,account.account_id);return sendJson(req,res,200,{ok:true},reqId);}
  if(req.method==='POST'&&url.pathname==='/api/accounts/logout'){const token=parseCookies(req.headers.cookie)[COOKIE_NAME];if(token)await query(`delete from franklin_sessions where session_hash=$1`,[sha256(`${SESSION_SECRET}:${token}`)]);clearSessionCookie(res);return sendJson(req,res,200,{ok:true},reqId);}
  if(req.method==='GET'&&url.pathname==='/api/accounts/me'){const session=await requireSession(req);const links=await query(`select profile_id,authority_state,verified_at from franklin_profile_links where account_id=$1 order by created_at`,[session.account_id]);const membership=await membershipForAccount(session.account_id);return sendJson(req,res,200,{ok:true,account:session,profileLinks:links.rows,membership},reqId);}
  if(req.method==='POST'&&url.pathname==='/api/profile-links'){const session=await requireSession(req);const body=await readBody(req);const profileId=normalizeProfile(body.profileId);const linkId=newId('link');await query(`insert into franklin_profile_links(link_id,account_id,profile_id) values($1,$2,$3) on conflict(account_id,profile_id) do update set updated_at=now()`,[linkId,session.account_id,profileId]);return sendJson(req,res,201,{ok:true,profileId,authorityState:'PENDING'},reqId);}
  if(req.method==='POST'&&url.pathname==='/api/membership/start'){if(!COMMERCE_ENABLED)throw publicError('COMMERCE_DISABLED','Franklin Navigator membership checkout is not open yet.',423);const session=await requireSession(req);const body=await readBody(req);const profileId=normalizeProfile(body.profileId);const plan=getPlan(body.lookupKey);if(!plan)throw publicError('PLAN_INVALID','Choose an available Franklin membership plan.');const verified=await query(`select 1 from franklin_profile_links where account_id=$1 and profile_id=$2 and authority_state='VERIFIED'`,[session.account_id,profileId]);if(!verified.rowCount)throw publicError('PROFILE_VERIFICATION_REQUIRED','Verify your connection to this Franklin profile before enrollment.',409);const link=(await query(`select url from franklin_payment_links where lookup_key=$1 and active=true`,[plan.lookupKey])).rows[0];if(!link)throw publicError('CHECKOUT_NOT_READY','This plan is not ready for enrollment.',503);const intentId=newId('checkout');await query(`insert into franklin_checkout_intents(intent_id,account_id,profile_id,lookup_key,expires_at) values($1,$2,$3,$4,now()+interval '24 hours')`,[intentId,session.account_id,profileId,plan.lookupKey]);const checkoutParams={client_reference_id:intentId,locked_prefilled_email:session.email};if(plan.couponEligible)checkoutParams.prefilled_promo_code=FOUNDING.promotionCode;const checkoutUrl=addLinkParams(link.url,checkoutParams);return sendJson(req,res,200,{ok:true,checkoutUrl,intentId,plan:{lookupKey:plan.lookupKey,regularUsd:plan.regularUsd,foundingUsd:plan.foundingUsd,autoRenew:plan.autoRenew,termMonths:plan.termMonths,billingMode:plan.billingMode,couponEligible:plan.couponEligible}},reqId);}
  if(req.method==='GET'&&url.pathname==='/api/membership/status'){const session=await requireSession(req);return sendJson(req,res,200,{ok:true,membership:await membershipForAccount(session.account_id)},reqId);}
  if(req.method==='POST'&&url.pathname==='/api/billing/portal'){await requireSession(req);if(!/^https:\/\/billing\.stripe\.com\//.test(STRIPE_PORTAL_LOGIN_URL))throw publicError('PORTAL_NOT_READY','Billing management is temporarily unavailable. Contact Franklin Navigator support.',503);return sendJson(req,res,200,{ok:true,url:STRIPE_PORTAL_LOGIN_URL},reqId);}
  if(req.method==='POST'&&url.pathname==='/api/onboarding'){const session=await requireSession(req);const membership=await membershipForAccount(session.account_id);if(!membership||!accessAllowed(membership.status,membership.current_period_end))throw publicError('ACTIVE_MEMBERSHIP_REQUIRED','An active membership is required.',403);const body=await readBody(req);const benefits=Array.isArray(body.selectedBenefits)?body.selectedBenefits.map(x=>safeText(x,60)).filter(Boolean).slice(0,12):[];const profileReady=Boolean(body.profileReady),growthDeskReady=Boolean(body.growthDeskReady);await query(`insert into franklin_onboarding(account_id,profile_id,organization_name,selected_benefits,preferred_language,profile_ready,growth_desk_ready,first_value_completed_at) values($1,$2,$3,$4::jsonb,$5,$6,$7,case when $6 and $7 then now() else null end) on conflict(account_id) do update set profile_id=excluded.profile_id,organization_name=excluded.organization_name,selected_benefits=excluded.selected_benefits,preferred_language=excluded.preferred_language,profile_ready=excluded.profile_ready,growth_desk_ready=excluded.growth_desk_ready,first_value_completed_at=case when excluded.profile_ready and excluded.growth_desk_ready then coalesce(franklin_onboarding.first_value_completed_at,now()) else franklin_onboarding.first_value_completed_at end,updated_at=now()`,[session.account_id,membership.profile_id,safeText(body.organizationName,160)||null,JSON.stringify(benefits),safeText(body.preferredLanguage,20)||'ENGLISH',profileReady,growthDeskReady]);if(profileReady&&growthDeskReady)await query(`update franklin_memberships set first_value_completed_at=coalesce(first_value_completed_at,now()),updated_at=now() where membership_id=$1`,[membership.membership_id]);return sendJson(req,res,200,{ok:true,firstValueCompleted:profileReady&&growthDeskReady},reqId);}
  if(req.method==='GET'&&url.pathname==='/api/entitlements/assertion'){const session=await requireSession(req);const membership=await membershipForAccount(session.account_id);if(!membership||!accessAllowed(membership.status,membership.current_period_end))throw publicError('ACTIVE_MEMBERSHIP_REQUIRED','An active membership is required.',403);const now=Math.floor(Date.now()/1000);const token=signAssertion(LOCAL_ASSERTION_SECRET,{iss:'LOCAL_COMMUNITY_PLATFORM',community:COMMUNITY,localRelease:RELEASE,memberKey:membership.membership_id,memberProfileId:membership.profile_id,membershipType:'COMMUNITY_MEMBERSHIP',planId:getPlan(membership.lookup_key)?.id,activePaidMember:true,iat:now,exp:now+900});return sendJson(req,res,200,{ok:true,assertion:token,expiresIn:900},reqId);}
  if(req.method==='POST'&&url.pathname==='/api/support/request'){const session=await sessionFor(req);const body=await readBody(req);const message=safeText(body.message,3000);if(message.length<10)throw publicError('MESSAGE_REQUIRED','Tell us how we can help.');const id=newId('support');await query(`insert into franklin_support_requests(request_id,account_id,profile_id,category,message,preferred_language) values($1,$2,$3,$4,$5,$6)`,[id,session?.account_id||null,safeText(body.profileId,110)||null,safeText(body.category,60).toUpperCase()||'GENERAL',message,safeText(body.preferredLanguage,20)||'ENGLISH']);return sendJson(req,res,201,{ok:true,requestId:id},reqId);}
  if(req.method==='POST'&&url.pathname==='/webhooks/stripe'){const raw=await readBody(req,true);if(!verifyStripeSignature({secret:STRIPE_WEBHOOK_SECRET,header:req.headers['stripe-signature'],rawBody:raw}))throw publicError('STRIPE_SIGNATURE_INVALID','Invalid Stripe signature.',400);const event=JSON.parse(raw.toString('utf8'));if(!event.livemode)throw publicError('LIVE_EVENT_REQUIRED','Only live Stripe events are accepted.',400);if(event.account&&event.account!==STRIPE_ACCOUNT_ID)throw publicError('STRIPE_ACCOUNT_MISMATCH','Stripe account does not match.',400);const result=await handleEvent({eventKey:`stripe:${event.id}`,source:'STRIPE_DIRECT',event,payloadHash:sha256(raw),reqId});return sendJson(req,res,200,{ok:true,...result},reqId);}
  if(req.method==='POST'&&url.pathname==='/internal/sre/events'){const raw=await readBody(req,true);const timestamp=req.headers['x-franklin-timestamp'];const signature=req.headers['x-franklin-signature'];if(!verifySignedRequest({secret:SRE_SHARED_SECRET,timestamp,signature,body:raw.toString('utf8')}))throw publicError('SRE_SIGNATURE_INVALID','Invalid signed event.',401);const envelope=JSON.parse(raw.toString('utf8'));if(envelope.community!==COMMUNITY||!envelope.event?.id)throw publicError('SRE_EVENT_INVALID','Invalid Franklin event envelope.');const result=await handleEvent({eventKey:`sre:${envelope.event.id}`,source:'SRE_SIGNED',event:envelope.event,payloadHash:sha256(raw),reqId});return sendJson(req,res,200,{ok:true,...result},reqId);}
  if(url.pathname.startsWith('/admin/')){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!ADMIN_TOKEN||!safeEqual(token,ADMIN_TOKEN))throw publicError('ADMIN_AUTH_REQUIRED','Administrative authorization required.',401);if(req.method==='POST'&&url.pathname==='/admin/payment-links/sync'){const body=await readBody(req);const links=Array.isArray(body.links)?body.links:[];if(links.length!==4)throw publicError('PAYMENT_LINK_COUNT_INVALID','Exactly four V4 checkout mappings are required.');const seen=new Set();await tx(async client=>{for(const item of links){const plan=getPlan(item.lookupKey);const paymentLinkId=safeText(item.paymentLinkId,80);const linkUrl=safeText(item.url,500);if(!plan||seen.has(plan.lookupKey)||!/^plink_[A-Za-z0-9]+$/.test(paymentLinkId)||!/^https:\/\/buy\.stripe\.com\//.test(linkUrl))throw publicError('PAYMENT_LINK_MAPPING_INVALID','Payment link mapping is invalid.');seen.add(plan.lookupKey);await client.query(`insert into franklin_payment_links(lookup_key,payment_link_id,url,metadata) values($1,$2,$3,$4::jsonb) on conflict(lookup_key) do update set payment_link_id=excluded.payment_link_id,url=excluded.url,active=true,validated_at=now(),metadata=excluded.metadata,updated_at=now()`,[plan.lookupKey,paymentLinkId,linkUrl,JSON.stringify({planId:plan.id,billingMode:plan.billingMode,termMonths:plan.termMonths,autoRenew:plan.autoRenew,couponEligible:plan.couponEligible})]);}await client.query(`update franklin_payment_links set active=false,updated_at=now() where not (lookup_key=any($1::text[]))`,[[...seen]]);});return sendJson(req,res,200,{ok:true,count:seen.size},reqId);}
    if(req.method==='POST'&&url.pathname==='/admin/profile-links/verify'){const body=await readBody(req);const profileId=normalizeProfile(body.profileId);const state=String(body.state||'VERIFIED').toUpperCase();if(!['VERIFIED','DISPUTED','REVOKED'].includes(state))throw publicError('AUTHORITY_STATE_INVALID','Invalid profile authority state.');const result=await query(`update franklin_profile_links set authority_state=$3,verified_at=case when $3='VERIFIED' then now() else verified_at end,updated_at=now() where account_id=$1 and profile_id=$2 returning account_id,profile_id,authority_state,verified_at`,[safeText(body.accountId,90),profileId,state]);if(!result.rowCount)throw publicError('PROFILE_LINK_NOT_FOUND','Profile link not found.',404);return sendJson(req,res,200,{ok:true,link:result.rows[0]},reqId);}
    if(req.method==='GET'&&url.pathname==='/admin/exceptions'){const dead=await query(`select * from franklin_dead_letters where state='OPEN' order by created_at desc limit 100`);const support=await query(`select request_id,account_id,profile_id,category,state,created_at from franklin_support_requests where state='OPEN' order by created_at desc limit 100`);return sendJson(req,res,200,{ok:true,deadLetters:dead.rows,supportRequests:support.rows},reqId);}}
  return sendJson(req,res,404,{ok:false,error:{code:'NOT_FOUND',message:'The requested Franklin membership-service route was not found.'}},reqId);
}catch(error){const status=Number(error.status||500);if(status>=500)console.error(JSON.stringify({event:'FRANKLIN_RUNTIME_ERROR',requestId:reqId,code:error.code||'INTERNAL_ERROR',message:String(error.message||error).slice(0,240),at:nowIso()}));return sendJson(req,res,status,{ok:false,error:{code:error.code||'INTERNAL_ERROR',message:status>=500?'The Franklin membership service could not complete this request.':String(error.message||'Request failed.')}},reqId);}}
const server=http.createServer(route);server.requestTimeout=15000;server.headersTimeout=10000;server.keepAliveTimeout=5000;
async function start(){try{await initializeDatabase();}catch(error){readyError=error;console.error(JSON.stringify({event:'FRANKLIN_RUNTIME_STARTUP_NOT_READY',release:RELEASE,error:String(error.message||error),at:nowIso()}));}server.listen(PORT,'0.0.0.0',()=>console.log(JSON.stringify({event:'FRANKLIN_RUNTIME_LISTENING',release:RELEASE,port:PORT,ready:!readyError,at:nowIso()})));}
async function shutdown(signal){console.log(JSON.stringify({event:'FRANKLIN_RUNTIME_SHUTDOWN',signal,at:nowIso()}));server.close(async()=>{if(pool)await pool.end().catch(()=>{});process.exit(0);});setTimeout(()=>process.exit(1),10000).unref();}
process.on('SIGTERM',()=>shutdown('SIGTERM'));process.on('SIGINT',()=>shutdown('SIGINT'));process.on('unhandledRejection',error=>console.error(JSON.stringify({event:'UNHANDLED_REJECTION',error:String(error),at:nowIso()})));
if(require.main===module)start();
module.exports={route,processCanonicalEvent,handleEvent,configStatus,normalizeProfile,commerceEnabled:COMMERCE_ENABLED};
