'use strict';
const http=require('node:http');
const {URL}=require('node:url');
const PORT=Number(process.env.PORT||10000);
const RELEASE='FR-NAV1.29.3-HF3.10.3';
const ORIGINS=new Set(['https://franklinnavigator.com','https://www.franklinnavigator.com','https://franklin-navigator.onrender.com']);
const BODY_LIMIT=16*1024;
const rate=new Map();
const now=()=>new Date().toISOString();
const text=v=>String(v||'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim();
const norm=v=>text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9\s'&.-]/g,' ').replace(/\s+/g,' ').trim();
const unescapeHtml=v=>String(v||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n)||32)).replace(/\s+/g,' ').trim();
const clientKey=req=>String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim();
function allow(req,res){const o=String(req.headers.origin||'');if(o&&ORIGINS.has(o)){res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS,GET');res.setHeader('Access-Control-Allow-Headers','Content-Type');}res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Cache-Control','no-store');}
function json(req,res,status,payload){allow(req,res);const b=JSON.stringify(payload);res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Content-Length',Buffer.byteLength(b));res.end(b)}
function limited(k,max=30,ms=3600000){const n=Date.now();let r=rate.get(k);if(!r||r.until<n)r={count:0,until:n+ms};r.count++;rate.set(k,r);return r.count<=max}
setInterval(()=>{const n=Date.now();for(const[k,v]of rate)if(v.until<n)rate.delete(k)},60000).unref();
async function body(req){let size=0,s='';for await(const c of req){size+=c.length;if(size>BODY_LIMIT)throw Object.assign(new Error('too_large'),{status:413});s+=c.toString('utf8')}try{return JSON.parse(s||'{}')}catch{throw Object.assign(new Error('bad_json'),{status:400})}}
const STOP=new Set('a an and are as at be by can could did do does for from get give go help how i in is it me my need of on or our please should show tell that the this to us want we what when where which who why with would you your franklin tn tennessee local online current latest information info about una un el la los las y o de en con para por que como cuando donde quien quiero necesito ayuda'.split(' '));
function terms(q){return [...new Set(norm(q).split(' ').filter(x=>x.length>2&&!STOP.has(x)))].slice(0,14)}
function decodeDdUrl(href){try{let h=unescapeHtml(href);if(h.startsWith('//'))h='https:'+h;const u=new URL(h,'https://html.duckduckgo.com');const raw=u.searchParams.get('uddg');return raw?decodeURIComponent(raw):u.href}catch{return''}}
function safeUrl(v){try{const u=new URL(v);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||!u.hostname.includes('.'))return'';if(/^(localhost|127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.)/i.test(u.hostname))return'';return u.href}catch{return''}}
function parseDuck(html){const out=[];const re=/<a[^>]+class="[^"]*result__a[^"]*"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>[\s\S]{0,1800}?(?:class="[^"]*result__snippet[^"]*"[^>]*>([\s\S]*?)<\/[^>]+>)?/gi;let m;while((m=re.exec(html))&&out.length<8){const url=safeUrl(decodeDdUrl(m[1]));if(!url)continue;out.push({title:unescapeHtml(m[2]),url,snippet:unescapeHtml(m[3]||'')})}return out}
function parseBing(xml){const out=[];const re=/<item>[\s\S]*?<title>([\s\S]*?)<\/title>[\s\S]*?<link>([\s\S]*?)<\/link>[\s\S]*?<description>([\s\S]*?)<\/description>[\s\S]*?<\/item>/gi;let m;while((m=re.exec(xml))&&out.length<8){const url=safeUrl(unescapeHtml(m[2]));if(url)out.push({title:unescapeHtml(m[1]),url,snippet:unescapeHtml(m[3])})}return out}
async function get(url,timeout=7000,max=1000000){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (compatible; FranklinNavigator/1.0; +https://franklinnavigator.com)'},redirect:'follow',signal:ctl.signal});if(!r.ok)throw Error('http_'+r.status);const len=Number(r.headers.get('content-length')||0);if(len>max)throw Error('too_large');const a=await r.arrayBuffer();if(a.byteLength>max)throw Error('too_large');return new TextDecoder().decode(a)}finally{clearTimeout(t)}}
async function searchWeb(q){const query=/\bfranklin\b/i.test(q)?q:`${q} Franklin Tennessee`;let rows=[];try{rows=parseDuck(await get('https://html.duckduckgo.com/html/?q='+encodeURIComponent(query),7500,900000))}catch{}if(rows.length<3){try{const b=parseBing(await get('https://www.bing.com/search?format=rss&q='+encodeURIComponent(query),7500,900000));const seen=new Set(rows.map(x=>x.url));for(const r of b)if(!seen.has(r.url)){seen.add(r.url);rows.push(r)}}catch{}}return rows.slice(0,6)}
function stripPage(html){return unescapeHtml(String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<!--([\s\S]*?)-->/g,' ').replace(/<(br|p|li|h1|h2|h3|h4|tr|div|section|article)[^>]*>/gi,'. ').replace(/<[^>]+>/g,' '))}
function sourceRank(url){try{const h=new URL(url).hostname.toLowerCase();if(h.endsWith('.gov')||h.includes('franklintn.gov')||h.includes('williamsoncounty-tn.gov'))return 30;if(h.endsWith('.edu'))return 18;if(h.includes('franklintn.gov')||h.includes('williamsoncounty'))return 14;return 0}catch{return 0}}
function sentences(s){return text(s).split(/(?<=[.!?])\s+/).map(x=>x.trim()).filter(x=>x.length>=30&&x.length<=420)}
function scoreSentence(s,q,url){const st=norm(s),ts=terms(q);let n=sourceRank(url);for(const t of ts)if(st.includes(t))n+=7;if(/\b(when|date|today|tonight|weekend|hours|open)\b/i.test(q)&&/\b(am|pm|monday|tuesday|wednesday|thursday|friday|saturday|sunday|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec|\d{1,2}[:/]\d{1,2})\b/i.test(s))n+=15;if(/\b(cost|price|fee|how much)\b/i.test(q)&&/\$\s?\d|fee|cost|price/i.test(s))n+=15;if(/\b(phone|call|number)\b/i.test(q)&&/(\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}/.test(s))n+=18;if(/\b(address|where)\b/i.test(q)&&/\b(st|street|rd|road|ave|avenue|dr|drive|blvd|boulevard|ln|lane|pkwy|parkway|franklin|tn)\b/i.test(s))n+=10;return n}
async function enrich(rows,q){const out=[];for(const r of rows.slice(0,4)){let page='';try{page=stripPage(await get(r.url,6000,900000))}catch{}const candidates=[...sentences(r.snippet),...sentences(page).slice(0,120)].map(s=>({s,score:scoreSentence(s,q,r.url)})).sort((a,b)=>b.score-a.score);out.push({...r,best:candidates[0]?.s||r.snippet||''})}return out}
function synthesize(rows,q){const pool=[];rows.forEach((r,i)=>{if(r.best)pool.push({s:r.best,url:r.url,title:r.title,score:scoreSentence(r.best,q,r.url),i})});pool.sort((a,b)=>b.score-a.score);const chosen=[];const seen=new Set();for(const x of pool){const k=norm(x.s).slice(0,90);if(!k||seen.has(k))continue;seen.add(k);chosen.push(x);if(chosen.length===3)break}if(!chosen.length)return{answer:'',confidence:'low'};const official=chosen.some(x=>sourceRank(x.url)>=30);const confidence=official||chosen.length>=2?'medium':'low';return{answer:chosen.map(x=>x.s).join(' '),confidence}}
async function research(q){const rows=await searchWeb(q);if(!rows.length)return{answer:'',sources:[],confidence:'low'};const enriched=await enrich(rows,q);const syn=synthesize(enriched,q);return{answer:syn.answer,sources:enriched.slice(0,4).map(x=>({title:x.title,url:x.url,snippet:text(x.best||x.snippet).slice(0,360)})),confidence:syn.confidence}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(req.method==='OPTIONS'){allow(req,res);res.statusCode=204;return res.end()}if(req.method==='GET'&&u.pathname==='/health')return json(req,res,200,{ok:true,release:RELEASE,mode:'PUBLIC_WEB_RESEARCH_EXTRACTIVE',at:now()});if(req.method!=='POST'||u.pathname!=='/api/research')return json(req,res,404,{ok:false,error:'NOT_FOUND'});const o=String(req.headers.origin||'');if(o&&!ORIGINS.has(o))return json(req,res,403,{ok:false,error:'ORIGIN_NOT_ALLOWED'});if(!limited(clientKey(req)))return json(req,res,429,{ok:false,error:'RATE_LIMITED'});const b=await body(req),q=text(b.q).slice(0,320);if(q.length<3)return json(req,res,400,{ok:false,error:'QUESTION_REQUIRED'});const result=await research(q);return json(req,res,200,{ok:true,question:q,...result,researchedAt:now(),note:'Public web research is used only when Franklin Navigator does not have enough verified local information. Changing details should be confirmed at the linked source.'})}catch(e){console.error(JSON.stringify({event:'assistant_runtime_error',message:String(e.message||e).slice(0,160),at:now()}));return json(req,res,Number(e.status||503),{ok:false,error:'RESEARCH_UNAVAILABLE',message:'Current web research could not be completed right now.'})}});
server.requestTimeout=18000;server.headersTimeout=10000;server.listen(PORT,'0.0.0.0',()=>console.log(JSON.stringify({event:'franklin_assistant_runtime_listening',release:RELEASE,port:PORT,at:now()})));
